### ISSUE TITLE
import numpy fails on armv7l architecture (Nexus 10, Android 5.1.1)

### ISSUE THREAD

**Issue by tigran123** [its-pointless/gcc_termux#39]
On Nexus 10 tablet (Android 5.1.1 armv7l architecture) trying to import numpy fails like this:

```
$ python
Python 3.6.6 (default, Jul 21 2018, 02:41:03) 
[GCC 4.2.1 Compatible Android (4691093 based on r316199) Clang 6.0.2 (https://a on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
$ python -c "import numpy"
WARNING: linker: multiarray.cpython-36m.so: unused DT entry: type 0x6ffffef5 arg 0x1538
WARNING: linker: umath.cpython-36m.so: unused DT entry: type 0x6ffffef5 arg 0xd08
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/numpy-1.14.5-py3.6-linux-armv7l.egg/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/numpy-1.14.5-py3.6-linux-armv7l.egg/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/numpy-1.14.5-py3.6-linux-armv7l.egg/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/numpy-1.14.5-py3.6-linux-armv7l.egg/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/numpy-1.14.5-py3.6-linux-armv7l.egg/numpy/core/__init__.py", line 34, in <module>
    from . import umath
ImportError: dlopen failed: cannot locate symbol "ctan" referenced by "umath.cpython-36m.so"...
$ pip list |grep numpy
numpy              1.14.5 
$ apt list | grep numpy

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

numpy/termux,now 1.14.5 arm [installed]
python2-numpy/termux 1.14.5 arm
$ uname -a
Linux localhost 3.4.67-g84ad5a4 #1 SMP PREEMPT Fri Nov 13 21:33:05 UTC 2015 armv7l Android
```

Of course I am using the proper repository, i.e. `https://its-pointless.github.io/files`. Btw, on Android 6.0 aarch64 architecture (LG G4 mobile) everything is working just fine. Any ideas how to fix it on Nexus 10?

**Comment by its-pointless** [comment]
ctan is in libgfortran.so.5 and i know how this happened so i will get around to it at some point today or tommorow.

**Comment by tigran123** [comment]
Thank you very much, I confirm that numpy and scipy are now working fine on Nexus 10! I have done `pkg upgrade` and picked up your new numpy and scipy packages.
