### ISSUE TITLE
scipy error when trying from scipy.signal import lfilter

### ISSUE THREAD

**Issue by aaronavi** [its-pointless/gcc_termux#44]
hi
I am using Python3 scipy on Termux and i am getting the following error:

Traceback (most recent call last):
  File "initiate_monitor.py", line 28, in <module>
    import batch_monitor
  File "/storage/emulated/0/DCIM/test/python/batch_monitor.py", line 45, in <module>
    import filter_data
  File "/storage/emulated/0/DCIM/test/python/filter_data.py", line 27, in <module>
    from eegfilt import eegfilt
  File "/storage/emulated/0/DCIM/test/python/eegfilt.py", line 2, in <module>
    from filtfilt import filtfilt
  File "/storage/emulated/0/DCIM/test/python/filtfilt.py", line 1, in <module>
    from scipy.signal import lfilter
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-i686.egg/scipy/signal/__init__.py", line 321, in <module>
    from .filter_design import *
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-i686.egg/scipy/signal/filter_design.py", line 18, in <module>
    from scipy import special, optimize, fftpack
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-i686.egg/scipy/optimize/__init__.py", line 271, in <module>
    from ._minimize import *                                                                                                                       File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-i686.egg/scipy/optimize/_minimize.py", line 30, in <module>
    from ._trustregion_krylov import _minimize_trust_krylov
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-i686.egg/scipy/optimize/_trustregion_krylov.py", line 2, in <module>
    from ._trlib import (get_trlib_quadratic_subproblem)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-i686.egg/scipy/optimize/_trlib/__init__.py", line 1, in <module>
    from ._trlib import TRLIBQuadraticSubproblem
  File "messagestream.pxd", line 5, in init scipy.optimize._trlib._trlib
ImportError: dlopen failed: cannot locate symbol "messagestream_open_memstream" referenced by "/data/data/com.termux/files/usr/lib/python3.6/site-packages/scipy-1.1.0-py3.6-linux-i686.egg/scipy/_lib/messagestream.cpython-36m.so"...

**Comment by its-pointless** [comment]
looking into this now

**Comment by its-pointless** [comment]
Iv fixed it just have to do some checking and upgrading versions and stuff.

**Comment by aaronavi** [comment]
thanks alot
