### ISSUE TITLE
import numpy fails (Android 8.1.0)

### ISSUE THREAD

**Issue by kragens** [its-pointless/gcc_termux#77]
on Moto G5 device importing numpy fails with following error:

$ python
Python 3.8.0 (default, Nov 20 2019, 20:46:44) 
[Clang 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf6 on linux
>>> import numpy
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/numpy-1.17.4-py3.8-linux-armv8l.egg/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/numpy-1.17.4-py3.8-linux-armv8l.egg/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/numpy-1.17.4-py3.8-linux-armv8l.egg/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen failed: cannot locate symbol "__aeabi_f2ulz" referenced by "/data/data/com.termux/files/usr/lib/python3.8/site-packages/numpy-1.17.4-py3.8-linux-armv8l.egg/numpy/core/_multiarray_umath.cpython-38.so"...

$ apt list| grep numpy
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
numpy/termux,now 1.17.4 arm [installed]

**Comment by its-pointless** [comment]
what happened is that python added ldflag -Wl,--as-needed. this means it wasn't linking libcompiler_rt.so on my machine because mine didn't need to link it but yours did. Fixing it now

**Comment by its-pointless** [comment]
should be fixed

**Comment by kragens** [comment]
It works fine now. Thank you very much for your great work
