### ISSUE TITLE
OpenCV python import error

### ISSUE THREAD

**Issue by sunskyhsh** [its-pointless/gcc_termux#79]
System information (version)
- OpenCV = 4.1.2
- python = 3.8.0
- Phone Brand = Xiaomi Mi 6
- Operating System = MIUI 11 based on Android 9
- Platform = Termux aarch64

After I installed opencv by using `apt install opencv`, I tried to import cv2 in python and got following ImportError:
```
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/cv2/__init__.py", line 89, in <module>
    bootstrap()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/cv2/__init__.py", line 79, in bootstrap
    import cv2
ImportError: dlopen failed: cannot locate symbol "_ZN6google8protobuf2io17CodedOutputStream21WriteVarint32SlowPathEj" referenced by "/data/data/com.termux/files/usr/lib/libopencv_dnn.so.4.1.2"...
```

Do you have any suggestions or solutions? Thanks.

**Comment by its-pointless** [comment]
Oh probably my fault since libprotobuf was updated.

**Comment by its-pointless** [comment]
should be fixed

**Comment by xhao79** [comment]
Hi, the problem shows up again

System Information:

- Phone Brand = Honor 9X
- Operating System = EMUI 10.1 based on Android 10
- Platform = Termux aarch64

The sources.list:
```
deb http://mirrors.tuna.tsinghua.edu.cn/termux stable main
deb https://its-pointless.github.io/files/24 termux extras
```

After installed the *Termux*
1. edit the sources.list
1. command:

   ```shell
    apt install coreutils gnupg
    wget https://its-pointless.github.io/pointless.gpg
    apt-key add pointless.gpg
    apt update
    apt install opencv
    ```

Then it shows up the error
```shell
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/cv2/__init__.py", line 96, in <module>
    bootstrap()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/cv2/__init__.py", line 86, in bootstrap
    import cv2
ImportError: dlopen failed: cannot locate symbol "_ZN6google8protobuf8internal17UnknownFieldParseEjPNS1_25InternalMetadataWithArenaEPKcPNS1_12ParseContextE" referenced by "/data/data/com.termux/files/usr/lib/libopencv_dnn.so.4.2.0"...
```

**Comment by TabulateJarl8** [comment]
Im getting the same error:
```python
>>> import cv2
Traceback (most recent call last):                           
File "<stdin>", line 1, in <module>
File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/cv2/__init__.py", line 96, in <module>
    bootstrap()
File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/cv2/__init__.py", line 86, in bootstrap
import cv2
ImportError: dlopen failed: cannot locate symbol "_ZN6google8protobuf8internal17UnknownFieldParseEjPNS1_25InternalMetadataWithArenaEPKcPNS1_12ParseContextE" referenced by "/data/data/com.termux/files/usr/lib/libopencv_dnn.so.4.2.0"...
```
